// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

#ifndef PROTOBUF_core_2eproto__INCLUDED
#define PROTOBUF_core_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
// @@protoc_insertion_point(includes)

namespace protobuf_core_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsqueryImpl();
void InitDefaultsquery();
void InitDefaultsresponseImpl();
void InitDefaultsresponse();
void InitDefaultsquery_client_connectImpl();
void InitDefaultsquery_client_connect();
void InitDefaultsres_client_connectImpl();
void InitDefaultsres_client_connect();
void InitDefaultsquery_pingImpl();
void InitDefaultsquery_ping();
void InitDefaultsres_pingImpl();
void InitDefaultsres_ping();
void InitDefaultsquery_account_pendingImpl();
void InitDefaultsquery_account_pending();
void InitDefaultsres_account_pendingImpl();
void InitDefaultsres_account_pending();
void InitDefaultsaccount_pendingImpl();
void InitDefaultsaccount_pending();
void InitDefaultsaccount_pending_block_infoImpl();
void InitDefaultsaccount_pending_block_info();
inline void InitDefaults() {
  InitDefaultsquery();
  InitDefaultsresponse();
  InitDefaultsquery_client_connect();
  InitDefaultsres_client_connect();
  InitDefaultsquery_ping();
  InitDefaultsres_ping();
  InitDefaultsquery_account_pending();
  InitDefaultsres_account_pending();
  InitDefaultsaccount_pending();
  InitDefaultsaccount_pending_block_info();
}
}  // namespace protobuf_core_2eproto
namespace nano {
namespace api {
class account_pending;
class account_pendingDefaultTypeInternal;
extern account_pendingDefaultTypeInternal _account_pending_default_instance_;
class account_pending_block_info;
class account_pending_block_infoDefaultTypeInternal;
extern account_pending_block_infoDefaultTypeInternal _account_pending_block_info_default_instance_;
class query;
class queryDefaultTypeInternal;
extern queryDefaultTypeInternal _query_default_instance_;
class query_account_pending;
class query_account_pendingDefaultTypeInternal;
extern query_account_pendingDefaultTypeInternal _query_account_pending_default_instance_;
class query_client_connect;
class query_client_connectDefaultTypeInternal;
extern query_client_connectDefaultTypeInternal _query_client_connect_default_instance_;
class query_ping;
class query_pingDefaultTypeInternal;
extern query_pingDefaultTypeInternal _query_ping_default_instance_;
class res_account_pending;
class res_account_pendingDefaultTypeInternal;
extern res_account_pendingDefaultTypeInternal _res_account_pending_default_instance_;
class res_client_connect;
class res_client_connectDefaultTypeInternal;
extern res_client_connectDefaultTypeInternal _res_client_connect_default_instance_;
class res_ping;
class res_pingDefaultTypeInternal;
extern res_pingDefaultTypeInternal _res_ping_default_instance_;
class response;
class responseDefaultTypeInternal;
extern responseDefaultTypeInternal _response_default_instance_;
}  // namespace api
}  // namespace nano
namespace nano {
namespace api {

enum QueryType {
  UNKOWN = 0,
  REGISTER_CALLBACK = 1,
  PING = 2,
  ACCOUNT_BALANCE = 3,
  ACCOUNT_BLOCK_COUNT = 4,
  ACCOUNT_PENDING = 5,
  QueryType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  QueryType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool QueryType_IsValid(int value);
const QueryType QueryType_MIN = UNKOWN;
const QueryType QueryType_MAX = ACCOUNT_PENDING;
const int QueryType_ARRAYSIZE = QueryType_MAX + 1;

const ::google::protobuf::EnumDescriptor* QueryType_descriptor();
inline const ::std::string& QueryType_Name(QueryType value) {
  return ::google::protobuf::internal::NameOfEnum(
    QueryType_descriptor(), value);
}
inline bool QueryType_Parse(
    const ::std::string& name, QueryType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<QueryType>(
    QueryType_descriptor(), name, value);
}
enum Result {
  OK = 0,
  GENERIC_ERROR = 1,
  INVALID_INPUT = 2,
  IO_ERROR = 3,
  Result_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Result_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Result_IsValid(int value);
const Result Result_MIN = OK;
const Result Result_MAX = IO_ERROR;
const int Result_ARRAYSIZE = Result_MAX + 1;

const ::google::protobuf::EnumDescriptor* Result_descriptor();
inline const ::std::string& Result_Name(Result value) {
  return ::google::protobuf::internal::NameOfEnum(
    Result_descriptor(), value);
}
inline bool Result_Parse(
    const ::std::string& name, Result* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Result>(
    Result_descriptor(), name, value);
}
// ===================================================================

class query : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.query) */ {
 public:
  query();
  virtual ~query();

  query(const query& from);

  inline query& operator=(const query& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  query(query&& from) noexcept
    : query() {
    *this = ::std::move(from);
  }

  inline query& operator=(query&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const query& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const query* internal_default_instance() {
    return reinterpret_cast<const query*>(
               &_query_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(query* other);
  friend void swap(query& a, query& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline query* New() const PROTOBUF_FINAL { return New(NULL); }

  query* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const query& from);
  void MergeFrom(const query& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(query* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .nano.api.QueryType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::nano::api::QueryType type() const;
  void set_type(::nano::api::QueryType value);

  // @@protoc_insertion_point(class_scope:nano.api.query)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsqueryImpl();
};
// -------------------------------------------------------------------

class response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.response) */ {
 public:
  response();
  virtual ~response();

  response(const response& from);

  inline response& operator=(const response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  response(response&& from) noexcept
    : response() {
    *this = ::std::move(from);
  }

  inline response& operator=(response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const response* internal_default_instance() {
    return reinterpret_cast<const response*>(
               &_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(response* other);
  friend void swap(response& a, response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline response* New() const PROTOBUF_FINAL { return New(NULL); }

  response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const response& from);
  void MergeFrom(const response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error = 3;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // .nano.api.Result result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::nano::api::Result result() const;
  void set_result(::nano::api::Result value);

  // .nano.api.QueryType type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::nano::api::QueryType type() const;
  void set_type(::nano::api::QueryType value);

  // sint32 error_code = 4;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 4;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:nano.api.response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  int result_;
  int type_;
  ::google::protobuf::int32 error_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsresponseImpl();
};
// -------------------------------------------------------------------

class query_client_connect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.query_client_connect) */ {
 public:
  query_client_connect();
  virtual ~query_client_connect();

  query_client_connect(const query_client_connect& from);

  inline query_client_connect& operator=(const query_client_connect& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  query_client_connect(query_client_connect&& from) noexcept
    : query_client_connect() {
    *this = ::std::move(from);
  }

  inline query_client_connect& operator=(query_client_connect&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const query_client_connect& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const query_client_connect* internal_default_instance() {
    return reinterpret_cast<const query_client_connect*>(
               &_query_client_connect_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(query_client_connect* other);
  friend void swap(query_client_connect& a, query_client_connect& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline query_client_connect* New() const PROTOBUF_FINAL { return New(NULL); }

  query_client_connect* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const query_client_connect& from);
  void MergeFrom(const query_client_connect& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(query_client_connect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string api_client_id = 2;
  void clear_api_client_id();
  static const int kApiClientIdFieldNumber = 2;
  const ::std::string& api_client_id() const;
  void set_api_client_id(const ::std::string& value);
  #if LANG_CXX11
  void set_api_client_id(::std::string&& value);
  #endif
  void set_api_client_id(const char* value);
  void set_api_client_id(const char* value, size_t size);
  ::std::string* mutable_api_client_id();
  ::std::string* release_api_client_id();
  void set_allocated_api_client_id(::std::string* api_client_id);

  // string api_key = 3;
  void clear_api_key();
  static const int kApiKeyFieldNumber = 3;
  const ::std::string& api_key() const;
  void set_api_key(const ::std::string& value);
  #if LANG_CXX11
  void set_api_key(::std::string&& value);
  #endif
  void set_api_key(const char* value);
  void set_api_key(const char* value, size_t size);
  ::std::string* mutable_api_key();
  ::std::string* release_api_key();
  void set_allocated_api_key(::std::string* api_key);

  // uint32 api_version = 1;
  void clear_api_version();
  static const int kApiVersionFieldNumber = 1;
  ::google::protobuf::uint32 api_version() const;
  void set_api_version(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nano.api.query_client_connect)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr api_client_id_;
  ::google::protobuf::internal::ArenaStringPtr api_key_;
  ::google::protobuf::uint32 api_version_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsquery_client_connectImpl();
};
// -------------------------------------------------------------------

class res_client_connect : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.res_client_connect) */ {
 public:
  res_client_connect();
  virtual ~res_client_connect();

  res_client_connect(const res_client_connect& from);

  inline res_client_connect& operator=(const res_client_connect& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  res_client_connect(res_client_connect&& from) noexcept
    : res_client_connect() {
    *this = ::std::move(from);
  }

  inline res_client_connect& operator=(res_client_connect&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const res_client_connect& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const res_client_connect* internal_default_instance() {
    return reinterpret_cast<const res_client_connect*>(
               &_res_client_connect_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(res_client_connect* other);
  friend void swap(res_client_connect& a, res_client_connect& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline res_client_connect* New() const PROTOBUF_FINAL { return New(NULL); }

  res_client_connect* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const res_client_connect& from);
  void MergeFrom(const res_client_connect& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(res_client_connect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 api_version = 1;
  void clear_api_version();
  static const int kApiVersionFieldNumber = 1;
  ::google::protobuf::uint32 api_version() const;
  void set_api_version(::google::protobuf::uint32 value);

  // uint32 node_version_major = 2;
  void clear_node_version_major();
  static const int kNodeVersionMajorFieldNumber = 2;
  ::google::protobuf::uint32 node_version_major() const;
  void set_node_version_major(::google::protobuf::uint32 value);

  // uint32 node_version_patch = 3;
  void clear_node_version_patch();
  static const int kNodeVersionPatchFieldNumber = 3;
  ::google::protobuf::uint32 node_version_patch() const;
  void set_node_version_patch(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nano.api.res_client_connect)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 api_version_;
  ::google::protobuf::uint32 node_version_major_;
  ::google::protobuf::uint32 node_version_patch_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsres_client_connectImpl();
};
// -------------------------------------------------------------------

class query_ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.query_ping) */ {
 public:
  query_ping();
  virtual ~query_ping();

  query_ping(const query_ping& from);

  inline query_ping& operator=(const query_ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  query_ping(query_ping&& from) noexcept
    : query_ping() {
    *this = ::std::move(from);
  }

  inline query_ping& operator=(query_ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const query_ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const query_ping* internal_default_instance() {
    return reinterpret_cast<const query_ping*>(
               &_query_ping_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(query_ping* other);
  friend void swap(query_ping& a, query_ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline query_ping* New() const PROTOBUF_FINAL { return New(NULL); }

  query_ping* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const query_ping& from);
  void MergeFrom(const query_ping& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(query_ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nano.api.query_ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsquery_pingImpl();
};
// -------------------------------------------------------------------

class res_ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.res_ping) */ {
 public:
  res_ping();
  virtual ~res_ping();

  res_ping(const res_ping& from);

  inline res_ping& operator=(const res_ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  res_ping(res_ping&& from) noexcept
    : res_ping() {
    *this = ::std::move(from);
  }

  inline res_ping& operator=(res_ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const res_ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const res_ping* internal_default_instance() {
    return reinterpret_cast<const res_ping*>(
               &_res_ping_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(res_ping* other);
  friend void swap(res_ping& a, res_ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline res_ping* New() const PROTOBUF_FINAL { return New(NULL); }

  res_ping* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const res_ping& from);
  void MergeFrom(const res_ping& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(res_ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:nano.api.res_ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsres_pingImpl();
};
// -------------------------------------------------------------------

class query_account_pending : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.query_account_pending) */ {
 public:
  query_account_pending();
  virtual ~query_account_pending();

  query_account_pending(const query_account_pending& from);

  inline query_account_pending& operator=(const query_account_pending& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  query_account_pending(query_account_pending&& from) noexcept
    : query_account_pending() {
    *this = ::std::move(from);
  }

  inline query_account_pending& operator=(query_account_pending&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const query_account_pending& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const query_account_pending* internal_default_instance() {
    return reinterpret_cast<const query_account_pending*>(
               &_query_account_pending_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(query_account_pending* other);
  friend void swap(query_account_pending& a, query_account_pending& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline query_account_pending* New() const PROTOBUF_FINAL { return New(NULL); }

  query_account_pending* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const query_account_pending& from);
  void MergeFrom(const query_account_pending& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(query_account_pending* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string accounts = 1;
  int accounts_size() const;
  void clear_accounts();
  static const int kAccountsFieldNumber = 1;
  const ::std::string& accounts(int index) const;
  ::std::string* mutable_accounts(int index);
  void set_accounts(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_accounts(int index, ::std::string&& value);
  #endif
  void set_accounts(int index, const char* value);
  void set_accounts(int index, const char* value, size_t size);
  ::std::string* add_accounts();
  void add_accounts(const ::std::string& value);
  #if LANG_CXX11
  void add_accounts(::std::string&& value);
  #endif
  void add_accounts(const char* value);
  void add_accounts(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& accounts() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_accounts();

  // .google.protobuf.StringValue threshold = 4;
  bool has_threshold() const;
  void clear_threshold();
  static const int kThresholdFieldNumber = 4;
  const ::google::protobuf::StringValue& threshold() const;
  ::google::protobuf::StringValue* release_threshold();
  ::google::protobuf::StringValue* mutable_threshold();
  void set_allocated_threshold(::google::protobuf::StringValue* threshold);

  // uint64 count = 2;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::uint64 count() const;
  void set_count(::google::protobuf::uint64 value);

  // bool source = 3;
  void clear_source();
  static const int kSourceFieldNumber = 3;
  bool source() const;
  void set_source(bool value);

  // @@protoc_insertion_point(class_scope:nano.api.query_account_pending)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> accounts_;
  ::google::protobuf::StringValue* threshold_;
  ::google::protobuf::uint64 count_;
  bool source_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsquery_account_pendingImpl();
};
// -------------------------------------------------------------------

class res_account_pending : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.res_account_pending) */ {
 public:
  res_account_pending();
  virtual ~res_account_pending();

  res_account_pending(const res_account_pending& from);

  inline res_account_pending& operator=(const res_account_pending& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  res_account_pending(res_account_pending&& from) noexcept
    : res_account_pending() {
    *this = ::std::move(from);
  }

  inline res_account_pending& operator=(res_account_pending&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const res_account_pending& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const res_account_pending* internal_default_instance() {
    return reinterpret_cast<const res_account_pending*>(
               &_res_account_pending_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(res_account_pending* other);
  friend void swap(res_account_pending& a, res_account_pending& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline res_account_pending* New() const PROTOBUF_FINAL { return New(NULL); }

  res_account_pending* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const res_account_pending& from);
  void MergeFrom(const res_account_pending& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(res_account_pending* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .nano.api.account_pending pending = 1;
  int pending_size() const;
  void clear_pending();
  static const int kPendingFieldNumber = 1;
  const ::nano::api::account_pending& pending(int index) const;
  ::nano::api::account_pending* mutable_pending(int index);
  ::nano::api::account_pending* add_pending();
  ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending >*
      mutable_pending();
  const ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending >&
      pending() const;

  // @@protoc_insertion_point(class_scope:nano.api.res_account_pending)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending > pending_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsres_account_pendingImpl();
};
// -------------------------------------------------------------------

class account_pending : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.account_pending) */ {
 public:
  account_pending();
  virtual ~account_pending();

  account_pending(const account_pending& from);

  inline account_pending& operator=(const account_pending& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  account_pending(account_pending&& from) noexcept
    : account_pending() {
    *this = ::std::move(from);
  }

  inline account_pending& operator=(account_pending&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const account_pending& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const account_pending* internal_default_instance() {
    return reinterpret_cast<const account_pending*>(
               &_account_pending_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(account_pending* other);
  friend void swap(account_pending& a, account_pending& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline account_pending* New() const PROTOBUF_FINAL { return New(NULL); }

  account_pending* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const account_pending& from);
  void MergeFrom(const account_pending& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(account_pending* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .nano.api.account_pending_block_info block_info = 2;
  int block_info_size() const;
  void clear_block_info();
  static const int kBlockInfoFieldNumber = 2;
  const ::nano::api::account_pending_block_info& block_info(int index) const;
  ::nano::api::account_pending_block_info* mutable_block_info(int index);
  ::nano::api::account_pending_block_info* add_block_info();
  ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending_block_info >*
      mutable_block_info();
  const ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending_block_info >&
      block_info() const;

  // string account = 1;
  void clear_account();
  static const int kAccountFieldNumber = 1;
  const ::std::string& account() const;
  void set_account(const ::std::string& value);
  #if LANG_CXX11
  void set_account(::std::string&& value);
  #endif
  void set_account(const char* value);
  void set_account(const char* value, size_t size);
  ::std::string* mutable_account();
  ::std::string* release_account();
  void set_allocated_account(::std::string* account);

  // @@protoc_insertion_point(class_scope:nano.api.account_pending)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending_block_info > block_info_;
  ::google::protobuf::internal::ArenaStringPtr account_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsaccount_pendingImpl();
};
// -------------------------------------------------------------------

class account_pending_block_info : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:nano.api.account_pending_block_info) */ {
 public:
  account_pending_block_info();
  virtual ~account_pending_block_info();

  account_pending_block_info(const account_pending_block_info& from);

  inline account_pending_block_info& operator=(const account_pending_block_info& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  account_pending_block_info(account_pending_block_info&& from) noexcept
    : account_pending_block_info() {
    *this = ::std::move(from);
  }

  inline account_pending_block_info& operator=(account_pending_block_info&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const account_pending_block_info& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const account_pending_block_info* internal_default_instance() {
    return reinterpret_cast<const account_pending_block_info*>(
               &_account_pending_block_info_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(account_pending_block_info* other);
  friend void swap(account_pending_block_info& a, account_pending_block_info& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline account_pending_block_info* New() const PROTOBUF_FINAL { return New(NULL); }

  account_pending_block_info* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const account_pending_block_info& from);
  void MergeFrom(const account_pending_block_info& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(account_pending_block_info* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string hash = 1;
  void clear_hash();
  static const int kHashFieldNumber = 1;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const char* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // string amount = 2;
  void clear_amount();
  static const int kAmountFieldNumber = 2;
  const ::std::string& amount() const;
  void set_amount(const ::std::string& value);
  #if LANG_CXX11
  void set_amount(::std::string&& value);
  #endif
  void set_amount(const char* value);
  void set_amount(const char* value, size_t size);
  ::std::string* mutable_amount();
  ::std::string* release_amount();
  void set_allocated_amount(::std::string* amount);

  // string source = 3;
  void clear_source();
  static const int kSourceFieldNumber = 3;
  const ::std::string& source() const;
  void set_source(const ::std::string& value);
  #if LANG_CXX11
  void set_source(::std::string&& value);
  #endif
  void set_source(const char* value);
  void set_source(const char* value, size_t size);
  ::std::string* mutable_source();
  ::std::string* release_source();
  void set_allocated_source(::std::string* source);

  // @@protoc_insertion_point(class_scope:nano.api.account_pending_block_info)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  ::google::protobuf::internal::ArenaStringPtr amount_;
  ::google::protobuf::internal::ArenaStringPtr source_;
  mutable int _cached_size_;
  friend struct ::protobuf_core_2eproto::TableStruct;
  friend void ::protobuf_core_2eproto::InitDefaultsaccount_pending_block_infoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// query

// .nano.api.QueryType type = 1;
inline void query::clear_type() {
  type_ = 0;
}
inline ::nano::api::QueryType query::type() const {
  // @@protoc_insertion_point(field_get:nano.api.query.type)
  return static_cast< ::nano::api::QueryType >(type_);
}
inline void query::set_type(::nano::api::QueryType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:nano.api.query.type)
}

// -------------------------------------------------------------------

// response

// .nano.api.Result result = 1;
inline void response::clear_result() {
  result_ = 0;
}
inline ::nano::api::Result response::result() const {
  // @@protoc_insertion_point(field_get:nano.api.response.result)
  return static_cast< ::nano::api::Result >(result_);
}
inline void response::set_result(::nano::api::Result value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:nano.api.response.result)
}

// .nano.api.QueryType type = 2;
inline void response::clear_type() {
  type_ = 0;
}
inline ::nano::api::QueryType response::type() const {
  // @@protoc_insertion_point(field_get:nano.api.response.type)
  return static_cast< ::nano::api::QueryType >(type_);
}
inline void response::set_type(::nano::api::QueryType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:nano.api.response.type)
}

// string error = 3;
inline void response::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& response::error() const {
  // @@protoc_insertion_point(field_get:nano.api.response.error)
  return error_.GetNoArena();
}
inline void response::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.response.error)
}
#if LANG_CXX11
inline void response::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.response.error)
}
#endif
inline void response::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.response.error)
}
inline void response::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.response.error)
}
inline ::std::string* response::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.response.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* response::release_error() {
  // @@protoc_insertion_point(field_release:nano.api.response.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void response::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:nano.api.response.error)
}

// sint32 error_code = 4;
inline void response::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 response::error_code() const {
  // @@protoc_insertion_point(field_get:nano.api.response.error_code)
  return error_code_;
}
inline void response::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:nano.api.response.error_code)
}

// -------------------------------------------------------------------

// query_client_connect

// uint32 api_version = 1;
inline void query_client_connect::clear_api_version() {
  api_version_ = 0u;
}
inline ::google::protobuf::uint32 query_client_connect::api_version() const {
  // @@protoc_insertion_point(field_get:nano.api.query_client_connect.api_version)
  return api_version_;
}
inline void query_client_connect::set_api_version(::google::protobuf::uint32 value) {
  
  api_version_ = value;
  // @@protoc_insertion_point(field_set:nano.api.query_client_connect.api_version)
}

// string api_client_id = 2;
inline void query_client_connect::clear_api_client_id() {
  api_client_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& query_client_connect::api_client_id() const {
  // @@protoc_insertion_point(field_get:nano.api.query_client_connect.api_client_id)
  return api_client_id_.GetNoArena();
}
inline void query_client_connect::set_api_client_id(const ::std::string& value) {
  
  api_client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.query_client_connect.api_client_id)
}
#if LANG_CXX11
inline void query_client_connect::set_api_client_id(::std::string&& value) {
  
  api_client_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.query_client_connect.api_client_id)
}
#endif
inline void query_client_connect::set_api_client_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  api_client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.query_client_connect.api_client_id)
}
inline void query_client_connect::set_api_client_id(const char* value, size_t size) {
  
  api_client_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.query_client_connect.api_client_id)
}
inline ::std::string* query_client_connect::mutable_api_client_id() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.query_client_connect.api_client_id)
  return api_client_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_client_connect::release_api_client_id() {
  // @@protoc_insertion_point(field_release:nano.api.query_client_connect.api_client_id)
  
  return api_client_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_client_connect::set_allocated_api_client_id(::std::string* api_client_id) {
  if (api_client_id != NULL) {
    
  } else {
    
  }
  api_client_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), api_client_id);
  // @@protoc_insertion_point(field_set_allocated:nano.api.query_client_connect.api_client_id)
}

// string api_key = 3;
inline void query_client_connect::clear_api_key() {
  api_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& query_client_connect::api_key() const {
  // @@protoc_insertion_point(field_get:nano.api.query_client_connect.api_key)
  return api_key_.GetNoArena();
}
inline void query_client_connect::set_api_key(const ::std::string& value) {
  
  api_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.query_client_connect.api_key)
}
#if LANG_CXX11
inline void query_client_connect::set_api_key(::std::string&& value) {
  
  api_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.query_client_connect.api_key)
}
#endif
inline void query_client_connect::set_api_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  api_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.query_client_connect.api_key)
}
inline void query_client_connect::set_api_key(const char* value, size_t size) {
  
  api_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.query_client_connect.api_key)
}
inline ::std::string* query_client_connect::mutable_api_key() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.query_client_connect.api_key)
  return api_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_client_connect::release_api_key() {
  // @@protoc_insertion_point(field_release:nano.api.query_client_connect.api_key)
  
  return api_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_client_connect::set_allocated_api_key(::std::string* api_key) {
  if (api_key != NULL) {
    
  } else {
    
  }
  api_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), api_key);
  // @@protoc_insertion_point(field_set_allocated:nano.api.query_client_connect.api_key)
}

// -------------------------------------------------------------------

// res_client_connect

// uint32 api_version = 1;
inline void res_client_connect::clear_api_version() {
  api_version_ = 0u;
}
inline ::google::protobuf::uint32 res_client_connect::api_version() const {
  // @@protoc_insertion_point(field_get:nano.api.res_client_connect.api_version)
  return api_version_;
}
inline void res_client_connect::set_api_version(::google::protobuf::uint32 value) {
  
  api_version_ = value;
  // @@protoc_insertion_point(field_set:nano.api.res_client_connect.api_version)
}

// uint32 node_version_major = 2;
inline void res_client_connect::clear_node_version_major() {
  node_version_major_ = 0u;
}
inline ::google::protobuf::uint32 res_client_connect::node_version_major() const {
  // @@protoc_insertion_point(field_get:nano.api.res_client_connect.node_version_major)
  return node_version_major_;
}
inline void res_client_connect::set_node_version_major(::google::protobuf::uint32 value) {
  
  node_version_major_ = value;
  // @@protoc_insertion_point(field_set:nano.api.res_client_connect.node_version_major)
}

// uint32 node_version_patch = 3;
inline void res_client_connect::clear_node_version_patch() {
  node_version_patch_ = 0u;
}
inline ::google::protobuf::uint32 res_client_connect::node_version_patch() const {
  // @@protoc_insertion_point(field_get:nano.api.res_client_connect.node_version_patch)
  return node_version_patch_;
}
inline void res_client_connect::set_node_version_patch(::google::protobuf::uint32 value) {
  
  node_version_patch_ = value;
  // @@protoc_insertion_point(field_set:nano.api.res_client_connect.node_version_patch)
}

// -------------------------------------------------------------------

// query_ping

// uint32 id = 1;
inline void query_ping::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 query_ping::id() const {
  // @@protoc_insertion_point(field_get:nano.api.query_ping.id)
  return id_;
}
inline void query_ping::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:nano.api.query_ping.id)
}

// -------------------------------------------------------------------

// res_ping

// uint32 id = 1;
inline void res_ping::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 res_ping::id() const {
  // @@protoc_insertion_point(field_get:nano.api.res_ping.id)
  return id_;
}
inline void res_ping::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:nano.api.res_ping.id)
}

// -------------------------------------------------------------------

// query_account_pending

// repeated string accounts = 1;
inline int query_account_pending::accounts_size() const {
  return accounts_.size();
}
inline void query_account_pending::clear_accounts() {
  accounts_.Clear();
}
inline const ::std::string& query_account_pending::accounts(int index) const {
  // @@protoc_insertion_point(field_get:nano.api.query_account_pending.accounts)
  return accounts_.Get(index);
}
inline ::std::string* query_account_pending::mutable_accounts(int index) {
  // @@protoc_insertion_point(field_mutable:nano.api.query_account_pending.accounts)
  return accounts_.Mutable(index);
}
inline void query_account_pending::set_accounts(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:nano.api.query_account_pending.accounts)
  accounts_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void query_account_pending::set_accounts(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:nano.api.query_account_pending.accounts)
  accounts_.Mutable(index)->assign(std::move(value));
}
#endif
inline void query_account_pending::set_accounts(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  accounts_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:nano.api.query_account_pending.accounts)
}
inline void query_account_pending::set_accounts(int index, const char* value, size_t size) {
  accounts_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:nano.api.query_account_pending.accounts)
}
inline ::std::string* query_account_pending::add_accounts() {
  // @@protoc_insertion_point(field_add_mutable:nano.api.query_account_pending.accounts)
  return accounts_.Add();
}
inline void query_account_pending::add_accounts(const ::std::string& value) {
  accounts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:nano.api.query_account_pending.accounts)
}
#if LANG_CXX11
inline void query_account_pending::add_accounts(::std::string&& value) {
  accounts_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:nano.api.query_account_pending.accounts)
}
#endif
inline void query_account_pending::add_accounts(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  accounts_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:nano.api.query_account_pending.accounts)
}
inline void query_account_pending::add_accounts(const char* value, size_t size) {
  accounts_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:nano.api.query_account_pending.accounts)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
query_account_pending::accounts() const {
  // @@protoc_insertion_point(field_list:nano.api.query_account_pending.accounts)
  return accounts_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
query_account_pending::mutable_accounts() {
  // @@protoc_insertion_point(field_mutable_list:nano.api.query_account_pending.accounts)
  return &accounts_;
}

// uint64 count = 2;
inline void query_account_pending::clear_count() {
  count_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 query_account_pending::count() const {
  // @@protoc_insertion_point(field_get:nano.api.query_account_pending.count)
  return count_;
}
inline void query_account_pending::set_count(::google::protobuf::uint64 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:nano.api.query_account_pending.count)
}

// bool source = 3;
inline void query_account_pending::clear_source() {
  source_ = false;
}
inline bool query_account_pending::source() const {
  // @@protoc_insertion_point(field_get:nano.api.query_account_pending.source)
  return source_;
}
inline void query_account_pending::set_source(bool value) {
  
  source_ = value;
  // @@protoc_insertion_point(field_set:nano.api.query_account_pending.source)
}

// .google.protobuf.StringValue threshold = 4;
inline bool query_account_pending::has_threshold() const {
  return this != internal_default_instance() && threshold_ != NULL;
}
inline const ::google::protobuf::StringValue& query_account_pending::threshold() const {
  const ::google::protobuf::StringValue* p = threshold_;
  // @@protoc_insertion_point(field_get:nano.api.query_account_pending.threshold)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* query_account_pending::release_threshold() {
  // @@protoc_insertion_point(field_release:nano.api.query_account_pending.threshold)
  
  ::google::protobuf::StringValue* temp = threshold_;
  threshold_ = NULL;
  return temp;
}
inline ::google::protobuf::StringValue* query_account_pending::mutable_threshold() {
  
  if (threshold_ == NULL) {
    threshold_ = new ::google::protobuf::StringValue;
  }
  // @@protoc_insertion_point(field_mutable:nano.api.query_account_pending.threshold)
  return threshold_;
}
inline void query_account_pending::set_allocated_threshold(::google::protobuf::StringValue* threshold) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(threshold_);
  }
  if (threshold) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast< ::google::protobuf::MessageLite*>(threshold)->GetArena();
    if (message_arena != submessage_arena) {
      threshold = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, threshold, submessage_arena);
    }
    
  } else {
    
  }
  threshold_ = threshold;
  // @@protoc_insertion_point(field_set_allocated:nano.api.query_account_pending.threshold)
}

// -------------------------------------------------------------------

// res_account_pending

// repeated .nano.api.account_pending pending = 1;
inline int res_account_pending::pending_size() const {
  return pending_.size();
}
inline void res_account_pending::clear_pending() {
  pending_.Clear();
}
inline const ::nano::api::account_pending& res_account_pending::pending(int index) const {
  // @@protoc_insertion_point(field_get:nano.api.res_account_pending.pending)
  return pending_.Get(index);
}
inline ::nano::api::account_pending* res_account_pending::mutable_pending(int index) {
  // @@protoc_insertion_point(field_mutable:nano.api.res_account_pending.pending)
  return pending_.Mutable(index);
}
inline ::nano::api::account_pending* res_account_pending::add_pending() {
  // @@protoc_insertion_point(field_add:nano.api.res_account_pending.pending)
  return pending_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending >*
res_account_pending::mutable_pending() {
  // @@protoc_insertion_point(field_mutable_list:nano.api.res_account_pending.pending)
  return &pending_;
}
inline const ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending >&
res_account_pending::pending() const {
  // @@protoc_insertion_point(field_list:nano.api.res_account_pending.pending)
  return pending_;
}

// -------------------------------------------------------------------

// account_pending

// string account = 1;
inline void account_pending::clear_account() {
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& account_pending::account() const {
  // @@protoc_insertion_point(field_get:nano.api.account_pending.account)
  return account_.GetNoArena();
}
inline void account_pending::set_account(const ::std::string& value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.account_pending.account)
}
#if LANG_CXX11
inline void account_pending::set_account(::std::string&& value) {
  
  account_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.account_pending.account)
}
#endif
inline void account_pending::set_account(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.account_pending.account)
}
inline void account_pending::set_account(const char* value, size_t size) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.account_pending.account)
}
inline ::std::string* account_pending::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.account_pending.account)
  return account_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* account_pending::release_account() {
  // @@protoc_insertion_point(field_release:nano.api.account_pending.account)
  
  return account_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void account_pending::set_allocated_account(::std::string* account) {
  if (account != NULL) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:nano.api.account_pending.account)
}

// repeated .nano.api.account_pending_block_info block_info = 2;
inline int account_pending::block_info_size() const {
  return block_info_.size();
}
inline void account_pending::clear_block_info() {
  block_info_.Clear();
}
inline const ::nano::api::account_pending_block_info& account_pending::block_info(int index) const {
  // @@protoc_insertion_point(field_get:nano.api.account_pending.block_info)
  return block_info_.Get(index);
}
inline ::nano::api::account_pending_block_info* account_pending::mutable_block_info(int index) {
  // @@protoc_insertion_point(field_mutable:nano.api.account_pending.block_info)
  return block_info_.Mutable(index);
}
inline ::nano::api::account_pending_block_info* account_pending::add_block_info() {
  // @@protoc_insertion_point(field_add:nano.api.account_pending.block_info)
  return block_info_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending_block_info >*
account_pending::mutable_block_info() {
  // @@protoc_insertion_point(field_mutable_list:nano.api.account_pending.block_info)
  return &block_info_;
}
inline const ::google::protobuf::RepeatedPtrField< ::nano::api::account_pending_block_info >&
account_pending::block_info() const {
  // @@protoc_insertion_point(field_list:nano.api.account_pending.block_info)
  return block_info_;
}

// -------------------------------------------------------------------

// account_pending_block_info

// string hash = 1;
inline void account_pending_block_info::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& account_pending_block_info::hash() const {
  // @@protoc_insertion_point(field_get:nano.api.account_pending_block_info.hash)
  return hash_.GetNoArena();
}
inline void account_pending_block_info::set_hash(const ::std::string& value) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.account_pending_block_info.hash)
}
#if LANG_CXX11
inline void account_pending_block_info::set_hash(::std::string&& value) {
  
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.account_pending_block_info.hash)
}
#endif
inline void account_pending_block_info::set_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.account_pending_block_info.hash)
}
inline void account_pending_block_info::set_hash(const char* value, size_t size) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.account_pending_block_info.hash)
}
inline ::std::string* account_pending_block_info::mutable_hash() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.account_pending_block_info.hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* account_pending_block_info::release_hash() {
  // @@protoc_insertion_point(field_release:nano.api.account_pending_block_info.hash)
  
  return hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void account_pending_block_info::set_allocated_hash(::std::string* hash) {
  if (hash != NULL) {
    
  } else {
    
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:nano.api.account_pending_block_info.hash)
}

// string amount = 2;
inline void account_pending_block_info::clear_amount() {
  amount_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& account_pending_block_info::amount() const {
  // @@protoc_insertion_point(field_get:nano.api.account_pending_block_info.amount)
  return amount_.GetNoArena();
}
inline void account_pending_block_info::set_amount(const ::std::string& value) {
  
  amount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.account_pending_block_info.amount)
}
#if LANG_CXX11
inline void account_pending_block_info::set_amount(::std::string&& value) {
  
  amount_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.account_pending_block_info.amount)
}
#endif
inline void account_pending_block_info::set_amount(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  amount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.account_pending_block_info.amount)
}
inline void account_pending_block_info::set_amount(const char* value, size_t size) {
  
  amount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.account_pending_block_info.amount)
}
inline ::std::string* account_pending_block_info::mutable_amount() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.account_pending_block_info.amount)
  return amount_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* account_pending_block_info::release_amount() {
  // @@protoc_insertion_point(field_release:nano.api.account_pending_block_info.amount)
  
  return amount_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void account_pending_block_info::set_allocated_amount(::std::string* amount) {
  if (amount != NULL) {
    
  } else {
    
  }
  amount_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), amount);
  // @@protoc_insertion_point(field_set_allocated:nano.api.account_pending_block_info.amount)
}

// string source = 3;
inline void account_pending_block_info::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& account_pending_block_info::source() const {
  // @@protoc_insertion_point(field_get:nano.api.account_pending_block_info.source)
  return source_.GetNoArena();
}
inline void account_pending_block_info::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:nano.api.account_pending_block_info.source)
}
#if LANG_CXX11
inline void account_pending_block_info::set_source(::std::string&& value) {
  
  source_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:nano.api.account_pending_block_info.source)
}
#endif
inline void account_pending_block_info::set_source(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:nano.api.account_pending_block_info.source)
}
inline void account_pending_block_info::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:nano.api.account_pending_block_info.source)
}
inline ::std::string* account_pending_block_info::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:nano.api.account_pending_block_info.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* account_pending_block_info::release_source() {
  // @@protoc_insertion_point(field_release:nano.api.account_pending_block_info.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void account_pending_block_info::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:nano.api.account_pending_block_info.source)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace api
}  // namespace nano

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::nano::api::QueryType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nano::api::QueryType>() {
  return ::nano::api::QueryType_descriptor();
}
template <> struct is_proto_enum< ::nano::api::Result> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nano::api::Result>() {
  return ::nano::api::Result_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_core_2eproto__INCLUDED
