/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accounts.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "accounts.pb-c.h"
void   req_account_pending__init
                     (ReqAccountPending         *message)
{
  static const ReqAccountPending init_value = REQ_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t req_account_pending__get_packed_size
                     (const ReqAccountPending *message)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_account_pending__pack
                     (const ReqAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_account_pending__pack_to_buffer
                     (const ReqAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqAccountPending *
       req_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqAccountPending *)
     protobuf_c_message_unpack (&req_account_pending__descriptor,
                                allocator, len, data);
}
void   req_account_pending__free_unpacked
                     (ReqAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_account_pending__init
                     (ResAccountPending         *message)
{
  static const ResAccountPending init_value = RES_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t res_account_pending__get_packed_size
                     (const ResAccountPending *message)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_account_pending__pack
                     (const ResAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_account_pending__pack_to_buffer
                     (const ResAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResAccountPending *
       res_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResAccountPending *)
     protobuf_c_message_unpack (&res_account_pending__descriptor,
                                allocator, len, data);
}
void   res_account_pending__free_unpacked
                     (ResAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending__init
                     (AccountPending         *message)
{
  static const AccountPending init_value = ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t account_pending__get_packed_size
                     (const AccountPending *message)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending__pack
                     (const AccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending__pack_to_buffer
                     (const AccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPending *
       account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPending *)
     protobuf_c_message_unpack (&account_pending__descriptor,
                                allocator, len, data);
}
void   account_pending__free_unpacked
                     (AccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending_block_info__init
                     (AccountPendingBlockInfo         *message)
{
  static const AccountPendingBlockInfo init_value = ACCOUNT_PENDING_BLOCK_INFO__INIT;
  *message = init_value;
}
size_t account_pending_block_info__get_packed_size
                     (const AccountPendingBlockInfo *message)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending_block_info__pack
                     (const AccountPendingBlockInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending_block_info__pack_to_buffer
                     (const AccountPendingBlockInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPendingBlockInfo *
       account_pending_block_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPendingBlockInfo *)
     protobuf_c_message_unpack (&account_pending_block_info__descriptor,
                                allocator, len, data);
}
void   account_pending_block_info__free_unpacked
                     (AccountPendingBlockInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor req_account_pending__field_descriptors[4] =
{
  {
    "accounts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReqAccountPending, n_accounts),
    offsetof(ReqAccountPending, accounts),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, threshold),
    &google__protobuf__string_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = accounts */
  1,   /* field[1] = count */
  2,   /* field[2] = source */
  3,   /* field[3] = threshold */
};
static const ProtobufCIntRange req_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor req_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "req_account_pending",
  "ReqAccountPending",
  "ReqAccountPending",
  "",
  sizeof(ReqAccountPending),
  4,
  req_account_pending__field_descriptors,
  req_account_pending__field_indices_by_name,
  1,  req_account_pending__number_ranges,
  (ProtobufCMessageInit) req_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_account_pending__field_descriptors[1] =
{
  {
    "pending",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ResAccountPending, n_pending),
    offsetof(ResAccountPending, pending),
    &account_pending__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = pending */
};
static const ProtobufCIntRange res_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_account_pending",
  "ResAccountPending",
  "ResAccountPending",
  "",
  sizeof(ResAccountPending),
  1,
  res_account_pending__field_descriptors,
  res_account_pending__field_indices_by_name,
  1,  res_account_pending__number_ranges,
  (ProtobufCMessageInit) res_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPending, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_info",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AccountPending, n_block_info),
    offsetof(AccountPending, block_info),
    &account_pending_block_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = block_info */
};
static const ProtobufCIntRange account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending",
  "AccountPending",
  "AccountPending",
  "",
  sizeof(AccountPending),
  2,
  account_pending__field_descriptors,
  account_pending__field_indices_by_name,
  1,  account_pending__number_ranges,
  (ProtobufCMessageInit) account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending_block_info__field_descriptors[3] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, amount),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending_block_info__field_indices_by_name[] = {
  1,   /* field[1] = amount */
  0,   /* field[0] = hash */
  2,   /* field[2] = source */
};
static const ProtobufCIntRange account_pending_block_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor account_pending_block_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending_block_info",
  "AccountPendingBlockInfo",
  "AccountPendingBlockInfo",
  "",
  sizeof(AccountPendingBlockInfo),
  3,
  account_pending_block_info__field_descriptors,
  account_pending_block_info__field_indices_by_name,
  1,  account_pending_block_info__number_ranges,
  (ProtobufCMessageInit) account_pending_block_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
