/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: core.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "core.pb-c.h"
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_ping__init
                     (ReqPing         *message)
{
  static const ReqPing init_value = REQ_PING__INIT;
  *message = init_value;
}
size_t req_ping__get_packed_size
                     (const ReqPing *message)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_ping__pack
                     (const ReqPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_ping__pack_to_buffer
                     (const ReqPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqPing *
       req_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqPing *)
     protobuf_c_message_unpack (&req_ping__descriptor,
                                allocator, len, data);
}
void   req_ping__free_unpacked
                     (ReqPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_ping__init
                     (ResPing         *message)
{
  static const ResPing init_value = RES_PING__INIT;
  *message = init_value;
}
size_t res_ping__get_packed_size
                     (const ResPing *message)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_ping__pack
                     (const ResPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_ping__pack_to_buffer
                     (const ResPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResPing *
       res_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResPing *)
     protobuf_c_message_unpack (&res_ping__descriptor,
                                allocator, len, data);
}
void   res_ping__free_unpacked
                     (ResPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_account_pending__init
                     (ReqAccountPending         *message)
{
  static const ReqAccountPending init_value = REQ_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t req_account_pending__get_packed_size
                     (const ReqAccountPending *message)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_account_pending__pack
                     (const ReqAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_account_pending__pack_to_buffer
                     (const ReqAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqAccountPending *
       req_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqAccountPending *)
     protobuf_c_message_unpack (&req_account_pending__descriptor,
                                allocator, len, data);
}
void   req_account_pending__free_unpacked
                     (ReqAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_account_pending__init
                     (ResAccountPending         *message)
{
  static const ResAccountPending init_value = RES_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t res_account_pending__get_packed_size
                     (const ResAccountPending *message)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_account_pending__pack
                     (const ResAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_account_pending__pack_to_buffer
                     (const ResAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResAccountPending *
       res_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResAccountPending *)
     protobuf_c_message_unpack (&res_account_pending__descriptor,
                                allocator, len, data);
}
void   res_account_pending__free_unpacked
                     (ResAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending__init
                     (AccountPending         *message)
{
  static const AccountPending init_value = ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t account_pending__get_packed_size
                     (const AccountPending *message)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending__pack
                     (const AccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending__pack_to_buffer
                     (const AccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPending *
       account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPending *)
     protobuf_c_message_unpack (&account_pending__descriptor,
                                allocator, len, data);
}
void   account_pending__free_unpacked
                     (AccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending_block_info__init
                     (AccountPendingBlockInfo         *message)
{
  static const AccountPendingBlockInfo init_value = ACCOUNT_PENDING_BLOCK_INFO__INIT;
  *message = init_value;
}
size_t account_pending_block_info__get_packed_size
                     (const AccountPendingBlockInfo *message)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending_block_info__pack
                     (const AccountPendingBlockInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending_block_info__pack_to_buffer
                     (const AccountPendingBlockInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPendingBlockInfo *
       account_pending_block_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPendingBlockInfo *)
     protobuf_c_message_unpack (&account_pending_block_info__descriptor,
                                allocator, len, data);
}
void   account_pending_block_info__free_unpacked
                     (AccountPendingBlockInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, type),
    &request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  1,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Response, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_category",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, error_category),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = error_category */
  1,   /* field[1] = error_code */
  2,   /* field[2] = error_message */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReqPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange req_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor req_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "req_ping",
  "ReqPing",
  "ReqPing",
  "",
  sizeof(ReqPing),
  1,
  req_ping__field_descriptors,
  req_ping__field_indices_by_name,
  1,  req_ping__number_ranges,
  (ProtobufCMessageInit) req_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange res_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_ping",
  "ResPing",
  "ResPing",
  "",
  sizeof(ResPing),
  1,
  res_ping__field_descriptors,
  res_ping__field_indices_by_name,
  1,  res_ping__number_ranges,
  (ProtobufCMessageInit) res_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_account_pending__field_descriptors[4] =
{
  {
    "accounts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ReqAccountPending, n_accounts),
    offsetof(ReqAccountPending, accounts),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ReqAccountPending, threshold),
    &google__protobuf__string_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = accounts */
  1,   /* field[1] = count */
  2,   /* field[2] = source */
  3,   /* field[3] = threshold */
};
static const ProtobufCIntRange req_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor req_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "req_account_pending",
  "ReqAccountPending",
  "ReqAccountPending",
  "",
  sizeof(ReqAccountPending),
  4,
  req_account_pending__field_descriptors,
  req_account_pending__field_indices_by_name,
  1,  req_account_pending__number_ranges,
  (ProtobufCMessageInit) req_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_account_pending__field_descriptors[1] =
{
  {
    "pending",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ResAccountPending, n_pending),
    offsetof(ResAccountPending, pending),
    &account_pending__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = pending */
};
static const ProtobufCIntRange res_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_account_pending",
  "ResAccountPending",
  "ResAccountPending",
  "",
  sizeof(ResAccountPending),
  1,
  res_account_pending__field_descriptors,
  res_account_pending__field_indices_by_name,
  1,  res_account_pending__number_ranges,
  (ProtobufCMessageInit) res_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPending, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_info",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AccountPending, n_block_info),
    offsetof(AccountPending, block_info),
    &account_pending_block_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = block_info */
};
static const ProtobufCIntRange account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending",
  "AccountPending",
  "AccountPending",
  "",
  sizeof(AccountPending),
  2,
  account_pending__field_descriptors,
  account_pending__field_indices_by_name,
  1,  account_pending__number_ranges,
  (ProtobufCMessageInit) account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending_block_info__field_descriptors[3] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, amount),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending_block_info__field_indices_by_name[] = {
  1,   /* field[1] = amount */
  0,   /* field[0] = hash */
  2,   /* field[2] = source */
};
static const ProtobufCIntRange account_pending_block_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor account_pending_block_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending_block_info",
  "AccountPendingBlockInfo",
  "AccountPendingBlockInfo",
  "",
  sizeof(AccountPendingBlockInfo),
  3,
  account_pending_block_info__field_descriptors,
  account_pending_block_info__field_indices_by_name,
  1,  account_pending_block_info__number_ranges,
  (ProtobufCMessageInit) account_pending_block_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue request_type__enum_values_by_number[6] =
{
  { "INVALID", "REQUEST_TYPE__INVALID", 0 },
  { "REGISTER_CALLBACK", "REQUEST_TYPE__REGISTER_CALLBACK", 1 },
  { "PING", "REQUEST_TYPE__PING", 2 },
  { "ACCOUNT_BALANCE", "REQUEST_TYPE__ACCOUNT_BALANCE", 3 },
  { "ACCOUNT_BLOCK_COUNT", "REQUEST_TYPE__ACCOUNT_BLOCK_COUNT", 4 },
  { "ACCOUNT_PENDING", "REQUEST_TYPE__ACCOUNT_PENDING", 5 },
};
static const ProtobufCIntRange request_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex request_type__enum_values_by_name[6] =
{
  { "ACCOUNT_BALANCE", 3 },
  { "ACCOUNT_BLOCK_COUNT", 4 },
  { "ACCOUNT_PENDING", 5 },
  { "INVALID", 0 },
  { "PING", 2 },
  { "REGISTER_CALLBACK", 1 },
};
const ProtobufCEnumDescriptor request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RequestType",
  "RequestType",
  "RequestType",
  "",
  6,
  request_type__enum_values_by_number,
  6,
  request_type__enum_values_by_name,
  1,
  request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
