/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: core.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "core.pb-c.h"
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_ping__init
                     (ReqPing         *message)
{
  static const ReqPing init_value = REQ_PING__INIT;
  *message = init_value;
}
size_t req_ping__get_packed_size
                     (const ReqPing *message)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_ping__pack
                     (const ReqPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_ping__pack_to_buffer
                     (const ReqPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqPing *
       req_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqPing *)
     protobuf_c_message_unpack (&req_ping__descriptor,
                                allocator, len, data);
}
void   req_ping__free_unpacked
                     (ReqPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_ping__init
                     (ResPing         *message)
{
  static const ResPing init_value = RES_PING__INIT;
  *message = init_value;
}
size_t res_ping__get_packed_size
                     (const ResPing *message)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_ping__pack
                     (const ResPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_ping__pack_to_buffer
                     (const ResPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResPing *
       res_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResPing *)
     protobuf_c_message_unpack (&res_ping__descriptor,
                                allocator, len, data);
}
void   res_ping__free_unpacked
                     (ResPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, type),
    &request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  1,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Response, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_category",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, error_category),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  3,   /* field[3] = error_category */
  1,   /* field[1] = error_code */
  2,   /* field[2] = error_message */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ReqPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange req_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor req_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "req_ping",
  "ReqPing",
  "ReqPing",
  "",
  sizeof(ReqPing),
  1,
  req_ping__field_descriptors,
  req_ping__field_indices_by_name,
  1,  req_ping__number_ranges,
  (ProtobufCMessageInit) req_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange res_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_ping",
  "ResPing",
  "ResPing",
  "",
  sizeof(ResPing),
  1,
  res_ping__field_descriptors,
  res_ping__field_indices_by_name,
  1,  res_ping__number_ranges,
  (ProtobufCMessageInit) res_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue apiversion__enum_values_by_number[2] =
{
  { "VERSION_INVALID", "APIVERSION__VERSION_INVALID", 0 },
  { "VERSION_MAJOR", "APIVERSION__VERSION_MAJOR", 1 },
};
static const ProtobufCIntRange apiversion__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex apiversion__enum_values_by_name[3] =
{
  { "VERSION_INVALID", 0 },
  { "VERSION_MAJOR", 1 },
  { "VERSION_MINOR", 0 },
};
const ProtobufCEnumDescriptor apiversion__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "APIVersion",
  "APIVersion",
  "APIVersion",
  "",
  2,
  apiversion__enum_values_by_number,
  3,
  apiversion__enum_values_by_name,
  1,
  apiversion__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue request_type__enum_values_by_number[5] =
{
  { "INVALID", "REQUEST_TYPE__INVALID", 0 },
  { "REGISTER_CALLBACK", "REQUEST_TYPE__REGISTER_CALLBACK", 1 },
  { "PING", "REQUEST_TYPE__PING", 2 },
  { "ACCOUNT_PENDING", "REQUEST_TYPE__ACCOUNT_PENDING", 100 },
  { "ADDRESS_VALID", "REQUEST_TYPE__ADDRESS_VALID", 1000 },
};
static const ProtobufCIntRange request_type__value_ranges[] = {
{0, 0},{100, 3},{1000, 4},{0, 5}
};
static const ProtobufCEnumValueIndex request_type__enum_values_by_name[5] =
{
  { "ACCOUNT_PENDING", 3 },
  { "ADDRESS_VALID", 4 },
  { "INVALID", 0 },
  { "PING", 2 },
  { "REGISTER_CALLBACK", 1 },
};
const ProtobufCEnumDescriptor request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RequestType",
  "RequestType",
  "RequestType",
  "",
  5,
  request_type__enum_values_by_number,
  5,
  request_type__enum_values_by_name,
  3,
  request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
