/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: core.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "core.pb-c.h"
void   query__init
                     (Query         *message)
{
  static const Query init_value = QUERY__INIT;
  *message = init_value;
}
size_t query__get_packed_size
                     (const Query *message)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query__pack
                     (const Query *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query__pack_to_buffer
                     (const Query *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Query *
       query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Query *)
     protobuf_c_message_unpack (&query__descriptor,
                                allocator, len, data);
}
void   query__free_unpacked
                     (Query *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_client_connect__init
                     (QueryClientConnect         *message)
{
  static const QueryClientConnect init_value = QUERY_CLIENT_CONNECT__INIT;
  *message = init_value;
}
size_t query_client_connect__get_packed_size
                     (const QueryClientConnect *message)
{
  assert(message->base.descriptor == &query_client_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_client_connect__pack
                     (const QueryClientConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_client_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_client_connect__pack_to_buffer
                     (const QueryClientConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_client_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryClientConnect *
       query_client_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryClientConnect *)
     protobuf_c_message_unpack (&query_client_connect__descriptor,
                                allocator, len, data);
}
void   query_client_connect__free_unpacked
                     (QueryClientConnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_client_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_client_connect__init
                     (ResClientConnect         *message)
{
  static const ResClientConnect init_value = RES_CLIENT_CONNECT__INIT;
  *message = init_value;
}
size_t res_client_connect__get_packed_size
                     (const ResClientConnect *message)
{
  assert(message->base.descriptor == &res_client_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_client_connect__pack
                     (const ResClientConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_client_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_client_connect__pack_to_buffer
                     (const ResClientConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_client_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResClientConnect *
       res_client_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResClientConnect *)
     protobuf_c_message_unpack (&res_client_connect__descriptor,
                                allocator, len, data);
}
void   res_client_connect__free_unpacked
                     (ResClientConnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_client_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_ping__init
                     (QueryPing         *message)
{
  static const QueryPing init_value = QUERY_PING__INIT;
  *message = init_value;
}
size_t query_ping__get_packed_size
                     (const QueryPing *message)
{
  assert(message->base.descriptor == &query_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_ping__pack
                     (const QueryPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_ping__pack_to_buffer
                     (const QueryPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryPing *
       query_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryPing *)
     protobuf_c_message_unpack (&query_ping__descriptor,
                                allocator, len, data);
}
void   query_ping__free_unpacked
                     (QueryPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_ping__init
                     (ResPing         *message)
{
  static const ResPing init_value = RES_PING__INIT;
  *message = init_value;
}
size_t res_ping__get_packed_size
                     (const ResPing *message)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_ping__pack
                     (const ResPing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_ping__pack_to_buffer
                     (const ResPing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResPing *
       res_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResPing *)
     protobuf_c_message_unpack (&res_ping__descriptor,
                                allocator, len, data);
}
void   res_ping__free_unpacked
                     (ResPing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_account_pending__init
                     (QueryAccountPending         *message)
{
  static const QueryAccountPending init_value = QUERY_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t query_account_pending__get_packed_size
                     (const QueryAccountPending *message)
{
  assert(message->base.descriptor == &query_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_account_pending__pack
                     (const QueryAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_account_pending__pack_to_buffer
                     (const QueryAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryAccountPending *
       query_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryAccountPending *)
     protobuf_c_message_unpack (&query_account_pending__descriptor,
                                allocator, len, data);
}
void   query_account_pending__free_unpacked
                     (QueryAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &query_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   res_account_pending__init
                     (ResAccountPending         *message)
{
  static const ResAccountPending init_value = RES_ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t res_account_pending__get_packed_size
                     (const ResAccountPending *message)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t res_account_pending__pack
                     (const ResAccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t res_account_pending__pack_to_buffer
                     (const ResAccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &res_account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResAccountPending *
       res_account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResAccountPending *)
     protobuf_c_message_unpack (&res_account_pending__descriptor,
                                allocator, len, data);
}
void   res_account_pending__free_unpacked
                     (ResAccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &res_account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending__init
                     (AccountPending         *message)
{
  static const AccountPending init_value = ACCOUNT_PENDING__INIT;
  *message = init_value;
}
size_t account_pending__get_packed_size
                     (const AccountPending *message)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending__pack
                     (const AccountPending *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending__pack_to_buffer
                     (const AccountPending *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPending *
       account_pending__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPending *)
     protobuf_c_message_unpack (&account_pending__descriptor,
                                allocator, len, data);
}
void   account_pending__free_unpacked
                     (AccountPending *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   account_pending_block_info__init
                     (AccountPendingBlockInfo         *message)
{
  static const AccountPendingBlockInfo init_value = ACCOUNT_PENDING_BLOCK_INFO__INIT;
  *message = init_value;
}
size_t account_pending_block_info__get_packed_size
                     (const AccountPendingBlockInfo *message)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t account_pending_block_info__pack
                     (const AccountPendingBlockInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t account_pending_block_info__pack_to_buffer
                     (const AccountPendingBlockInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AccountPendingBlockInfo *
       account_pending_block_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AccountPendingBlockInfo *)
     protobuf_c_message_unpack (&account_pending_block_info__descriptor,
                                allocator, len, data);
}
void   account_pending_block_info__free_unpacked
                     (AccountPendingBlockInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &account_pending_block_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Query, type),
    &query_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query",
  "Query",
  "Query",
  "",
  sizeof(Query),
  1,
  query__field_descriptors,
  query__field_indices_by_name,
  1,  query__number_ranges,
  (ProtobufCMessageInit) query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[4] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, result),
    &result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &query_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Response, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Response, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  2,   /* field[2] = error */
  3,   /* field[3] = error_code */
  0,   /* field[0] = result */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  4,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_client_connect__field_descriptors[3] =
{
  {
    "api_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(QueryClientConnect, api_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api_client_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QueryClientConnect, api_client_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "api_key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(QueryClientConnect, api_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_client_connect__field_indices_by_name[] = {
  1,   /* field[1] = api_client_id */
  2,   /* field[2] = api_key */
  0,   /* field[0] = api_version */
};
static const ProtobufCIntRange query_client_connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor query_client_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query_client_connect",
  "QueryClientConnect",
  "QueryClientConnect",
  "",
  sizeof(QueryClientConnect),
  3,
  query_client_connect__field_descriptors,
  query_client_connect__field_indices_by_name,
  1,  query_client_connect__number_ranges,
  (ProtobufCMessageInit) query_client_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_client_connect__field_descriptors[3] =
{
  {
    "api_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResClientConnect, api_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_version_major",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResClientConnect, node_version_major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_version_patch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResClientConnect, node_version_patch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_client_connect__field_indices_by_name[] = {
  0,   /* field[0] = api_version */
  1,   /* field[1] = node_version_major */
  2,   /* field[2] = node_version_patch */
};
static const ProtobufCIntRange res_client_connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor res_client_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_client_connect",
  "ResClientConnect",
  "ResClientConnect",
  "",
  sizeof(ResClientConnect),
  3,
  res_client_connect__field_descriptors,
  res_client_connect__field_indices_by_name,
  1,  res_client_connect__number_ranges,
  (ProtobufCMessageInit) res_client_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(QueryPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange query_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query_ping",
  "QueryPing",
  "QueryPing",
  "",
  sizeof(QueryPing),
  1,
  query_ping__field_descriptors,
  query_ping__field_indices_by_name,
  1,  query_ping__number_ranges,
  (ProtobufCMessageInit) query_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_ping__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ResPing, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_ping__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange res_ping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_ping",
  "ResPing",
  "ResPing",
  "",
  sizeof(ResPing),
  1,
  res_ping__field_descriptors,
  res_ping__field_indices_by_name,
  1,  res_ping__number_ranges,
  (ProtobufCMessageInit) res_ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_account_pending__field_descriptors[4] =
{
  {
    "accounts",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(QueryAccountPending, n_accounts),
    offsetof(QueryAccountPending, accounts),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(QueryAccountPending, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(QueryAccountPending, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(QueryAccountPending, threshold),
    &google__protobuf__string_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = accounts */
  1,   /* field[1] = count */
  2,   /* field[2] = source */
  3,   /* field[3] = threshold */
};
static const ProtobufCIntRange query_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor query_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "query_account_pending",
  "QueryAccountPending",
  "QueryAccountPending",
  "",
  sizeof(QueryAccountPending),
  4,
  query_account_pending__field_descriptors,
  query_account_pending__field_indices_by_name,
  1,  query_account_pending__number_ranges,
  (ProtobufCMessageInit) query_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor res_account_pending__field_descriptors[1] =
{
  {
    "pending",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ResAccountPending, n_pending),
    offsetof(ResAccountPending, pending),
    &account_pending__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned res_account_pending__field_indices_by_name[] = {
  0,   /* field[0] = pending */
};
static const ProtobufCIntRange res_account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor res_account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "res_account_pending",
  "ResAccountPending",
  "ResAccountPending",
  "",
  sizeof(ResAccountPending),
  1,
  res_account_pending__field_descriptors,
  res_account_pending__field_indices_by_name,
  1,  res_account_pending__number_ranges,
  (ProtobufCMessageInit) res_account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPending, account),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_info",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AccountPending, n_block_info),
    offsetof(AccountPending, block_info),
    &account_pending_block_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = block_info */
};
static const ProtobufCIntRange account_pending__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor account_pending__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending",
  "AccountPending",
  "AccountPending",
  "",
  sizeof(AccountPending),
  2,
  account_pending__field_descriptors,
  account_pending__field_indices_by_name,
  1,  account_pending__number_ranges,
  (ProtobufCMessageInit) account_pending__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor account_pending_block_info__field_descriptors[3] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, amount),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AccountPendingBlockInfo, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned account_pending_block_info__field_indices_by_name[] = {
  1,   /* field[1] = amount */
  0,   /* field[0] = hash */
  2,   /* field[2] = source */
};
static const ProtobufCIntRange account_pending_block_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor account_pending_block_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "account_pending_block_info",
  "AccountPendingBlockInfo",
  "AccountPendingBlockInfo",
  "",
  sizeof(AccountPendingBlockInfo),
  3,
  account_pending_block_info__field_descriptors,
  account_pending_block_info__field_indices_by_name,
  1,  account_pending_block_info__number_ranges,
  (ProtobufCMessageInit) account_pending_block_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue query_type__enum_values_by_number[6] =
{
  { "UNKOWN", "QUERY_TYPE__UNKOWN", 0 },
  { "REGISTER_CALLBACK", "QUERY_TYPE__REGISTER_CALLBACK", 1 },
  { "PING", "QUERY_TYPE__PING", 2 },
  { "ACCOUNT_BALANCE", "QUERY_TYPE__ACCOUNT_BALANCE", 3 },
  { "ACCOUNT_BLOCK_COUNT", "QUERY_TYPE__ACCOUNT_BLOCK_COUNT", 4 },
  { "ACCOUNT_PENDING", "QUERY_TYPE__ACCOUNT_PENDING", 5 },
};
static const ProtobufCIntRange query_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex query_type__enum_values_by_name[6] =
{
  { "ACCOUNT_BALANCE", 3 },
  { "ACCOUNT_BLOCK_COUNT", 4 },
  { "ACCOUNT_PENDING", 5 },
  { "PING", 2 },
  { "REGISTER_CALLBACK", 1 },
  { "UNKOWN", 0 },
};
const ProtobufCEnumDescriptor query_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "QueryType",
  "QueryType",
  "QueryType",
  "",
  6,
  query_type__enum_values_by_number,
  6,
  query_type__enum_values_by_name,
  1,
  query_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue result__enum_values_by_number[4] =
{
  { "OK", "RESULT__OK", 0 },
  { "GENERIC_ERROR", "RESULT__GENERIC_ERROR", 1 },
  { "INVALID_INPUT", "RESULT__INVALID_INPUT", 2 },
  { "IO_ERROR", "RESULT__IO_ERROR", 3 },
};
static const ProtobufCIntRange result__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex result__enum_values_by_name[4] =
{
  { "GENERIC_ERROR", 1 },
  { "INVALID_INPUT", 2 },
  { "IO_ERROR", 3 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Result",
  "Result",
  "Result",
  "",
  4,
  result__enum_values_by_number,
  4,
  result__enum_values_by_name,
  1,
  result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
